package tracker;

import static com.codename1.ui.CN.*;

import com.codename1.notifications.LocalNotificationCallback;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.ui.Toolbar;
import tracker.Pages.DailySurveyPg2GUI;
import tracker.Pages.LoginGUI;
import tracker.Pages.SurveyPageOne;
import tracker.Pages.SurveyPg1;

/**
 * This file was generated by
 * <a href="https://www.codenameone.com/">Codename One</a>
 * for the purpose of building native mobile applications using Java.
 */
public class CoreApp implements LocalNotificationCallback {

    private Form current;
    private Resources theme;

    public void init(final Object context) {
        // use two network threads instead of one
        updateNetworkThreadCount(2);
        theme = UIManager.initFirstTheme("/theme");
        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

    }
    
    public void start() {

        if (current != null) {
            current.show();
            return;
        }


        //LoginGUI login = new LoginGUI();
        //login.show();
        //SurveyPageOne test = new SurveyPageOne();
        //test.show();
        SurveyPg1 test = new SurveyPg1();
        test.show();



        //main.Show();

    }

    public void stop() {
        current = getCurrentForm();
        if (current instanceof Dialog) {
            ((Dialog) current).dispose();
            current = getCurrentForm();
        }
    }
    
    public void destroy() {
    }

    @Override
    public void localNotificationReceived(final String notificationId) {

        //Testing purposes
        System.out.println("Recieved local notification" + notificationId);

    }
}
