package GUItests;

import com.codename1.testing.AbstractTest;

import com.codename1.ui.Display;

public class defaultPg2Test extends AbstractTest {
    public boolean runTest() throws Exception {
        waitForFormName("DailySurveyPgTwoGUI");
        assertTitle("DailySurveyPgTwoGUI");
        clickButtonByName("backButton");
        waitForFormName("DailySurveyPgOneGUI");
        assertTitle("DailySurveyPgOneGUI");
        clickButtonByName("confirmButton");
        waitForFormName("DailySurveyPgTwoGUI");
        assertTitle("DailySurveyPgTwoGUI");
        assertLabel("topInset", "");
        assertLabel("Label", "");
        assertLabel("depressedLabel", "");
        assertLabel("panicLabel", "");
        assertLabel("exerciseLabel", "");
        assertLabel("sleepLabel", "");
        assertLabel("depressedButtonYes", "");
        assertLabel("yesterdayLabel", "");
        assertLabel("backButton", "");
        assertLabel("depressedButtonNo", "");
        assertLabel("panicButtonNo", "");
        assertLabel("panicButtonYes", "");
        assertLabel("exerciseButtonYes", "");
        assertLabel("exerciseButtonNo", "");
        assertLabel("yesButtonInset", "");
        assertLabel("noButtonInset", "");
        assertLabel("continueButton", "");
        assertTextArea("sleepInput", "");
        assertTextArea("sugarInput", "");
        clickButtonByName("depressedButtonNo");
        assertLabel("topInset", "");
        assertLabel("Label", "");
        assertLabel("depressedLabel", "");
        assertLabel("panicLabel", "");
        assertLabel("exerciseLabel", "");
        assertLabel("sleepLabel", "");
        assertLabel("depressedButtonYes", "");
        assertLabel("yesterdayLabel", "");
        assertLabel("backButton", "");
        assertLabel("depressedButtonNo", "");
        assertLabel("panicButtonNo", "");
        assertLabel("panicButtonYes", "");
        assertLabel("exerciseButtonYes", "");
        assertLabel("exerciseButtonNo", "");
        assertLabel("yesButtonInset", "");
        assertLabel("noButtonInset", "");
        assertLabel("continueButton", "");
        clickButtonByName("panicButtonYes");
        clickButtonByName("exerciseButtonNo");
        assertLabel("topInset", "");
        assertLabel("Label", "");
        assertLabel("depressedLabel", "");
        assertLabel("panicLabel", "");
        assertLabel("exerciseLabel", "");
        assertLabel("sleepLabel", "");
        assertLabel("depressedButtonYes", "");
        assertLabel("yesterdayLabel", "");
        assertLabel("backButton", "");
        assertLabel("depressedButtonNo", "");
        assertLabel("panicButtonNo", "");
        assertLabel("panicButtonYes", "");
        assertLabel("exerciseButtonYes", "");
        assertLabel("exerciseButtonNo", "");
        assertLabel("yesButtonInset", "");
        assertLabel("noButtonInset", "");
        assertLabel("continueButton", "");
        clickButtonByName("exerciseButtonYes");
        clickButtonByName("panicButtonNo");
        assertLabel("topInset", "");
        assertLabel("Label", "");
        assertLabel("depressedLabel", "");
        assertLabel("panicLabel", "");
        assertLabel("exerciseLabel", "");
        assertLabel("sleepLabel", "");
        assertLabel("depressedButtonYes", "");
        assertLabel("yesterdayLabel", "");
        assertLabel("backButton", "");
        assertLabel("depressedButtonNo", "");
        assertLabel("panicButtonNo", "");
        assertLabel("panicButtonYes", "");
        assertLabel("exerciseButtonYes", "");
        assertLabel("exerciseButtonNo", "");
        assertLabel("yesButtonInset", "");
        assertLabel("noButtonInset", "");
        assertLabel("continueButton", "");
        setText("sleepInput", "lette");
        setText("sugarInput", "12");
        assertTextArea("sleepInput", "lette");
        assertTextArea("sugarInput", "12");
        clickButtonByName("continueButton");
        waitForFormTitle("Error!");
        Display.getInstance().getCurrent().setName("Form_1");
        goBack();
        waitForFormName("DailySurveyPgTwoGUI");
        setText("sleepInput", "12");
        assertTextArea("sleepInput", "12");
        assertTextArea("sugarInput", "12");
        clickButtonByName("continueButton");
        return true;
    }
}
