package GUItests;

import com.codename1.testing.AbstractTest;

import com.codename1.ui.Display;

public class levelsTest extends AbstractTest {
    public boolean runTest() throws Exception {
        waitForFormName("DailySurveyPgOneGUI");
        assertTitle("DailySurveyPgOneGUI");
        assertLabel("topInset", "");
        assertLabel("confirmButton", "");
        assertLabel("backButton", "");
        assertLabel("moodLabels", "");
        assertLabel("stressLabel", "");
        assertLabel("anxietyLabel", "");
        assertLabel("confidenceLabel", "");
        assertLabel("overallLabel", "");
        assertLabel("stressSlider", "");
        assertLabel("anxietySlider", "");
        assertLabel("confidenceSlider", "");
        assertLabel("overallSlider", "");
        assertLabel("stressNum", "");
        assertLabel("anxietyNum", "");
        assertLabel("confidenceNum", "");
        assertLabel("overallNum", "");
        clickButtonByName("backButton");
        waitForFormName("NeedDailyGUI");
        assertTitle("NeedDailyGUI");
        clickButtonByName("TakeSurvey");
        waitForFormName("DailySurveyPgOneGUI");
        assertTitle("DailySurveyPgOneGUI");
        pointerPress(0.57528955f, 0.48630136f, "confidenceSlider");
        waitFor(126);
        pointerRelease(0.57528955f, 0.48630136f, "confidenceSlider");
        assertLabel("topInset", "");
        assertLabel("confirmButton", "");
        assertLabel("backButton", "");
        assertLabel("moodLabels", "");
        assertLabel("stressLabel", "");
        assertLabel("anxietyLabel", "");
        assertLabel("confidenceLabel", "");
        assertLabel("overallLabel", "");
        assertLabel("stressSlider", "");
        assertLabel("anxietySlider", "");
        assertLabel("confidenceSlider", "");
        assertLabel("overallSlider", "");
        assertLabel("stressNum", "");
        assertLabel("anxietyNum", "");
        assertLabel("confidenceNum", "57");
        assertLabel("overallNum", "");
        pointerPress(0.40625f, 0.4651163f, "overallSlider");
        waitFor(110);
        pointerRelease(0.40625f, 0.4651163f, "overallSlider");
        assertLabel("topInset", "");
        assertLabel("confirmButton", "");
        assertLabel("backButton", "");
        assertLabel("moodLabels", "");
        assertLabel("stressLabel", "");
        assertLabel("anxietyLabel", "");
        assertLabel("confidenceLabel", "");
        assertLabel("overallLabel", "");
        assertLabel("stressSlider", "");
        assertLabel("anxietySlider", "");
        assertLabel("confidenceSlider", "");
        assertLabel("overallSlider", "");
        assertLabel("stressNum", "");
        assertLabel("anxietyNum", "");
        assertLabel("confidenceNum", "57");
        assertLabel("overallNum", "40");
        pointerPress(0.890625f, 0.5116279f, "overallSlider");
        waitFor(155);
        pointerRelease(0.890625f, 0.5116279f, "overallSlider");
        assertLabel("topInset", "");
        assertLabel("confirmButton", "");
        assertLabel("backButton", "");
        assertLabel("moodLabels", "");
        assertLabel("stressLabel", "");
        assertLabel("anxietyLabel", "");
        assertLabel("confidenceLabel", "");
        assertLabel("overallLabel", "");
        assertLabel("stressSlider", "");
        assertLabel("anxietySlider", "");
        assertLabel("confidenceSlider", "");
        assertLabel("overallSlider", "");
        assertLabel("stressNum", "");
        assertLabel("anxietyNum", "");
        assertLabel("confidenceNum", "57");
        assertLabel("overallNum", "89");
        clickButtonByName("confirmButton");
        waitForFormName("DailySurveyPgTwoGUI");
        assertTitle("DailySurveyPgTwoGUI");
        return true;
    }
}
