package tests;

import com.codename1.testing.AbstractTest;

import com.codename1.ui.Display;

public class runthrough1 extends AbstractTest {
    public boolean runTest() throws Exception {
        waitForFormName("MainPage");
        assertTitle("Mental Tracker");
        assertLabel("topInset", "");
        assertLabel("confirmButton", "");
        assertLabel("Prompt", "Daily Tracking Is Ready!");
        clickButtonByName("confirmButton");
        waitForFormName("UserPromptPage");
        assertTitle("Track Your Mind");
        assertLabel("TopInset", "");
        assertLabel("Prompt", "Rate your recent mood (higher is better!)");
        assertLabel("Label", "Recent Mood");
        assertLabel("confirmButton", "");
        assertLabel("BackButton", "");
        assertLabel("Slider", "");
        pointerPress(0.7346041f, 0.45714286f, "Slider");
        waitFor(58);
        pointerRelease(0.7346041f, 0.45714286f, "Slider");
        assertLabel("TopInset", "");
        assertLabel("Prompt", "Rate your recent mood (higher is better!)");
        assertLabel("Label", "Recent Mood");
        assertLabel("confirmButton", "");
        assertLabel("BackButton", "");
        assertLabel("Slider", "14");
        pointerPress(0.1994135f, 0.45714286f, "Slider");
        waitFor(89);
        pointerRelease(0.1994135f, 0.45714286f, "Slider");
        assertLabel("TopInset", "");
        assertLabel("Prompt", "Rate your recent mood (higher is better!)");
        assertLabel("Label", "Recent Mood");
        assertLabel("confirmButton", "");
        assertLabel("BackButton", "");
        assertLabel("Slider", "3");
        clickButtonByName("confirmButton");
        waitForFormName("UserPromptPage");
        assertTitle("Track Your Mind");
        assertLabel("TopInset", "");
        assertLabel("Prompt", "Did you exercise?");
        assertLabel("Label", "Exercise Past Day");
        assertLabel("confirmButton", "");
        assertLabel("BackButton", "");
        assertLabel("depressedButtonNo", "");
        assertLabel("depressedButtonYes", "");
        clickButtonByName("confirmButton");
        assertTitle("Track Your Mind");
        clickButtonByName("depressedButtonNo");
        assertLabel("TopInset", "");
        assertLabel("Prompt", "Did you exercise?");
        assertLabel("Label", "Exercise Past Day");
        assertLabel("confirmButton", "");
        assertLabel("BackButton", "");
        assertLabel("depressedButtonNo", "");
        assertLabel("depressedButtonYes", "");
        clickButtonByName("depressedButtonYes");
        assertLabel("TopInset", "");
        assertLabel("Prompt", "Did you exercise?");
        assertLabel("Label", "Exercise Past Day");
        assertLabel("confirmButton", "");
        assertLabel("BackButton", "");
        assertLabel("depressedButtonNo", "");
        assertLabel("depressedButtonYes", "");
        clickButtonByName("confirmButton");
        waitForFormName("UserPromptPage");
        assertTitle("Track Your Mind");
        pointerPress(0.47947213f, 0.44f, "Slider");
        waitFor(59);
        pointerRelease(0.47947213f, 0.44f, "Slider");
        assertLabel("TopInset", "");
        assertLabel("Prompt", "How stressed are you?");
        assertLabel("Label", "Overall Stress");
        assertLabel("confirmButton", "");
        assertLabel("BackButton", "");
        assertLabel("Slider", "9");
        pointerPress(0.9633431f, 0.49142858f, "Slider");
        waitFor(75);
        pointerRelease(0.9633431f, 0.49142858f, "Slider");
        assertLabel("TopInset", "");
        assertLabel("Prompt", "How stressed are you?");
        assertLabel("Label", "Overall Stress");
        assertLabel("confirmButton", "");
        assertLabel("BackButton", "");
        assertLabel("Slider", "19");
        clickButtonByName("confirmButton");
        waitForFormName("UserPromptPage");
        assertTitle("Track Your Mind");
        assertLabel("TopInset", "");
        assertLabel("Prompt", "How anxious do you feel?");
        assertLabel("Label", "Overall Anxiety");
        assertLabel("confirmButton", "");
        assertLabel("BackButton", "");
        assertLabel("Slider", "");
        pointerPress(0.30938417f, 0.49142858f, "Slider");
        waitFor(53);
        pointerRelease(0.30938417f, 0.49142858f, "Slider");
        assertLabel("TopInset", "");
        assertLabel("Prompt", "How anxious do you feel?");
        assertLabel("Label", "Overall Anxiety");
        assertLabel("confirmButton", "");
        assertLabel("BackButton", "");
        assertLabel("Slider", "6");
        clickButtonByName("confirmButton");
        waitForFormName("UserPromptPage");
        assertTitle("Track Your Mind");
        assertLabel("TopInset", "");
        assertLabel("Prompt", "Any experiences symptoms of panic?");
        assertLabel("Label", "Recent Panic Symptoms");
        assertLabel("confirmButton", "");
        assertLabel("BackButton", "");
        assertLabel("depressedButtonNo", "");
        assertLabel("depressedButtonYes", "");
        clickButtonByName("depressedButtonNo");
        assertLabel("TopInset", "");
        assertLabel("Prompt", "Any experiences symptoms of panic?");
        assertLabel("Label", "Recent Panic Symptoms");
        assertLabel("confirmButton", "");
        assertLabel("BackButton", "");
        assertLabel("depressedButtonNo", "");
        assertLabel("depressedButtonYes", "");
        clickButtonByName("depressedButtonYes");
        assertLabel("TopInset", "");
        assertLabel("Prompt", "Any experiences symptoms of panic?");
        assertLabel("Label", "Recent Panic Symptoms");
        assertLabel("confirmButton", "");
        assertLabel("BackButton", "");
        assertLabel("depressedButtonNo", "");
        assertLabel("depressedButtonYes", "");
        clickButtonByName("confirmButton");
        waitForFormName("UserPromptPage");
        assertTitle("Track Your Mind");
        assertLabel("TopInset", "");
        assertLabel("Prompt", "Mood shifts experienced since the last check-in?");
        assertLabel("Label", "Mood Shifts Past Day");
        assertLabel("confirmButton", "");
        assertLabel("BackButton", "");
        assertLabel("Slider", "");
        pointerPress(0.7683284f, 0.50857145f, "Slider");
        waitFor(88);
        pointerRelease(0.7683284f, 0.50857145f, "Slider");
        clickButtonByName("confirmButton");
        waitForFormName("UserPromptPage");
        assertTitle("Track Your Mind");
        assertLabel("TopInset", "");
        assertLabel("Prompt", "Grams of sugar consumed");
        assertLabel("Label", "Sugar Past Day");
        assertLabel("confirmButton", "");
        assertLabel("BackButton", "");
        assertLabel("Slider", "");
        pointerPress(0.7346041f, 0.49142858f, "Slider");
        waitFor(89);
        pointerRelease(0.7346041f, 0.49142858f, "Slider");
        assertLabel("TopInset", "");
        assertLabel("Prompt", "Grams of sugar consumed");
        assertLabel("Label", "Sugar Past Day");
        assertLabel("confirmButton", "");
        assertLabel("BackButton", "");
        assertLabel("Slider", "14");
        clickButtonByName("confirmButton");
        waitForFormName("UserPromptPage");
        assertTitle("Track Your Mind");
        assertLabel("TopInset", "");
        assertLabel("Prompt", "Have you experienced a depressed mood?");
        assertLabel("Label", "Depressed Mood");
        assertLabel("confirmButton", "");
        assertLabel("BackButton", "");
        assertLabel("depressedButtonNo", "");
        assertLabel("depressedButtonYes", "");
        clickButtonByName("depressedButtonNo");
        assertLabel("TopInset", "");
        assertLabel("Prompt", "Have you experienced a depressed mood?");
        assertLabel("Label", "Depressed Mood");
        assertLabel("confirmButton", "");
        assertLabel("BackButton", "");
        assertLabel("depressedButtonNo", "");
        assertLabel("depressedButtonYes", "");
        clickButtonByName("depressedButtonYes");
        assertLabel("TopInset", "");
        assertLabel("Prompt", "Have you experienced a depressed mood?");
        assertLabel("Label", "Depressed Mood");
        assertLabel("confirmButton", "");
        assertLabel("BackButton", "");
        assertLabel("depressedButtonNo", "");
        assertLabel("depressedButtonYes", "");
        clickButtonByName("confirmButton");
        waitForFormName("UserPromptPage");
        assertTitle("Track Your Mind");
        assertLabel("TopInset", "");
        assertLabel("Prompt", "How much sleep did you get last night?");
        assertLabel("Label", "Sleep");
        assertLabel("confirmButton", "");
        assertLabel("BackButton", "");
        assertTextArea("sleepInput", "");
        setText("sleepInput", "12");
        waitFor(2932);
        gameKeyPress(Display.GAME_FIRE);
        assertTextArea("sleepInput", "12");
        clickButtonByName("confirmButton");
        waitForFormName("UserPromptPage");
        assertTitle("Track Your Mind");
        pointerPress(0.33870968f, 0.47428572f, "Slider");
        waitFor(90);
        pointerRelease(0.33870968f, 0.47428572f, "Slider");
        assertLabel("TopInset", "");
        assertLabel("Prompt", "How confident have you felt recently?");
        assertLabel("Label", "Overall Confidence Level");
        assertLabel("confirmButton", "");
        assertLabel("BackButton", "");
        assertLabel("Slider", "6");
        clickButtonByName("confirmButton");
        waitForFormName("MainPage");
        assertTitle("Mental Tracker");
        return true;
    }
}
