package tracker.Pages;
public class SurveyPageOne extends com.codename1.ui.Form {
    public SurveyPageOne() {
        this(com.codename1.ui.util.Resources.getGlobalResources());
    }
    
    public SurveyPageOne(com.codename1.ui.util.Resources resourceObjectInstance) {
        initGuiBuilderComponents(resourceObjectInstance);
    }
    
//-- DON'T EDIT BELOW THIS LINE!!!
    protected com.codename1.ui.Container gui_Box_Layout_Y = new com.codename1.ui.Container(new com.codename1.ui.layouts.BoxLayout(com.codename1.ui.layouts.BoxLayout.Y_AXIS));
    protected com.codename1.ui.Label gui_Label_1 = new com.codename1.ui.Label();
    protected com.codename1.ui.Container gui_Box_Layout_X = new com.codename1.ui.Container(new com.codename1.ui.layouts.BoxLayout(com.codename1.ui.layouts.BoxLayout.X_AXIS));
    protected com.codename1.ui.Label gui_Label_14 = new com.codename1.ui.Label();
    protected com.codename1.ui.Slider gui_Slider_5 = new com.codename1.ui.Slider();
    protected com.codename1.ui.Label gui_Label_10 = new com.codename1.ui.Label();
    protected com.codename1.ui.Slider gui_Slider_2 = new com.codename1.ui.Slider();
    protected com.codename1.ui.Label gui_Label_13 = new com.codename1.ui.Label();
    protected com.codename1.ui.Slider gui_Slider_4 = new com.codename1.ui.Slider();
    protected com.codename1.ui.Label gui_Label_11 = new com.codename1.ui.Label();
    protected com.codename1.ui.Slider gui_Slider_3 = new com.codename1.ui.Slider();
    protected com.codename1.ui.Label gui_Label_12 = new com.codename1.ui.Label();
    protected com.codename1.ui.Label gui_Label_15 = new com.codename1.ui.Label();
    protected com.codename1.ui.Container gui_Box_Layout_X_1 = new com.codename1.ui.Container(new com.codename1.ui.layouts.BoxLayout(com.codename1.ui.layouts.BoxLayout.X_AXIS));
    protected com.codename1.ui.Label gui_Label_2 = new com.codename1.ui.Label();
    protected com.codename1.ui.Label gui_Label_3 = new com.codename1.ui.Label();
    protected com.codename1.ui.Label gui_Label_4 = new com.codename1.ui.Label();
    protected com.codename1.ui.Label gui_Label_5 = new com.codename1.ui.Label();
    protected com.codename1.ui.Label gui_Label_6 = new com.codename1.ui.Label();
    protected com.codename1.ui.Label gui_Label_7 = new com.codename1.ui.Label();
    protected com.codename1.ui.Label gui_Label_8 = new com.codename1.ui.Label();
    protected com.codename1.ui.Label gui_Label_9 = new com.codename1.ui.Label();
    protected com.codename1.ui.Label gui_Label = new com.codename1.ui.Label();
    protected com.codename1.ui.Label gui_Label_16 = new com.codename1.ui.Label();
    protected com.codename1.ui.Label gui_Label_17 = new com.codename1.ui.Label();


// <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initGuiBuilderComponents(com.codename1.ui.util.Resources resourceObjectInstance) {
        setLayout(new com.codename1.ui.layouts.LayeredLayout());
        setInlineStylesTheme(resourceObjectInstance);
        setScrollableY(false);
                setInlineStylesTheme(resourceObjectInstance);
        setInlineAllStyles("bgColor:efefef; bgImage:;");
        setTitle("SurveyPageOne");
        setName("SurveyPageOne");
        addComponent(gui_Box_Layout_Y);
        gui_Box_Layout_Y.setPreferredSizeStr("inherit 147.61905mm");
                gui_Box_Layout_Y.setInlineStylesTheme(resourceObjectInstance);
        gui_Box_Layout_Y.setName("Box_Layout_Y");
        ((com.codename1.ui.layouts.LayeredLayout)gui_Box_Layout_Y.getParent().getLayout()).setInsets(gui_Box_Layout_Y, "5.291005mm auto 10.526316% auto").setReferenceComponents(gui_Box_Layout_Y, "1 1 -1 1 ").setReferencePositions(gui_Box_Layout_Y, "1.0 0.0 0.0 0.0");
        gui_Box_Layout_Y.addComponent(gui_Label_1);
        gui_Box_Layout_Y.addComponent(gui_Box_Layout_X);
        gui_Box_Layout_X.setPreferredSizeStr("inherit 111.111115mm");
        gui_Box_Layout_X.setScrollableX(false);
        gui_Box_Layout_X.setScrollableY(false);
                gui_Box_Layout_X.setInlineStylesTheme(resourceObjectInstance);
        gui_Box_Layout_X.setName("Box_Layout_X");
        gui_Box_Layout_X.addComponent(gui_Label_14);
        gui_Box_Layout_X.addComponent(gui_Slider_5);
        gui_Box_Layout_X.addComponent(gui_Label_10);
        gui_Box_Layout_X.addComponent(gui_Slider_2);
        gui_Box_Layout_X.addComponent(gui_Label_13);
        gui_Box_Layout_X.addComponent(gui_Slider_4);
        gui_Box_Layout_X.addComponent(gui_Label_11);
        gui_Box_Layout_X.addComponent(gui_Slider_3);
        gui_Box_Layout_X.addComponent(gui_Label_12);
        gui_Box_Layout_X.addComponent(gui_Label_15);
        gui_Label_14.setText("Label");
                gui_Label_14.setInlineStylesTheme(resourceObjectInstance);
        gui_Label_14.setName("Label_14");
        gui_Slider_5.setEditable(true);
        gui_Slider_5.setFocusable(true);
        gui_Slider_5.setVertical(true);
                gui_Slider_5.setInlineStylesTheme(resourceObjectInstance);
        gui_Slider_5.setName("Slider_5");
        gui_Slider_5.setGap(2);
        gui_Slider_5.setIncrements(1);
        gui_Slider_5.setProgress(1);
        gui_Label_10.setText("Label");
                gui_Label_10.setInlineStylesTheme(resourceObjectInstance);
        gui_Label_10.setName("Label_10");
        gui_Slider_2.setEditable(true);
        gui_Slider_2.setFocusable(true);
        gui_Slider_2.setVertical(true);
                gui_Slider_2.setInlineStylesTheme(resourceObjectInstance);
        gui_Slider_2.setName("Slider_2");
        gui_Slider_2.setGap(2);
        gui_Slider_2.setIncrements(1);
        gui_Slider_2.setProgress(8);
        gui_Label_13.setText("Label");
                gui_Label_13.setInlineStylesTheme(resourceObjectInstance);
        gui_Label_13.setName("Label_13");
        gui_Slider_4.setEditable(true);
        gui_Slider_4.setFocusable(true);
        gui_Slider_4.setVertical(true);
                gui_Slider_4.setInlineStylesTheme(resourceObjectInstance);
        gui_Slider_4.setName("Slider_4");
        gui_Slider_4.setIncrements(1);
        gui_Slider_4.setProgress(10);
        gui_Label_11.setText("Label");
                gui_Label_11.setInlineStylesTheme(resourceObjectInstance);
        gui_Label_11.setName("Label_11");
        gui_Slider_3.setEditable(true);
        gui_Slider_3.setFocusable(true);
        gui_Slider_3.setVertical(true);
                gui_Slider_3.setInlineStylesTheme(resourceObjectInstance);
        gui_Slider_3.setName("Slider_3");
        gui_Slider_3.setIncrements(1);
        gui_Slider_3.setProgress(1);
        gui_Label_12.setText("Label");
                gui_Label_12.setInlineStylesTheme(resourceObjectInstance);
        gui_Label_12.setName("Label_12");
        gui_Label_15.setText("Label");
                gui_Label_15.setInlineStylesTheme(resourceObjectInstance);
        gui_Label_15.setName("Label_15");
        gui_Box_Layout_Y.addComponent(gui_Box_Layout_X_1);
                gui_Box_Layout_X_1.setInlineStylesTheme(resourceObjectInstance);
        gui_Box_Layout_X_1.setName("Box_Layout_X_1");
        gui_Box_Layout_X_1.addComponent(gui_Label_2);
        gui_Box_Layout_X_1.addComponent(gui_Label_3);
        gui_Box_Layout_X_1.addComponent(gui_Label_4);
        gui_Box_Layout_X_1.addComponent(gui_Label_5);
        gui_Box_Layout_X_1.addComponent(gui_Label_6);
        gui_Box_Layout_X_1.addComponent(gui_Label_7);
        gui_Box_Layout_X_1.addComponent(gui_Label_8);
        gui_Box_Layout_X_1.addComponent(gui_Label_9);
        gui_Label_2.setText("Search:");
                gui_Label_2.setInlineStylesTheme(resourceObjectInstance);
        gui_Label_2.setName("Label_2");
        gui_Label_3.setText("Label");
                gui_Label_3.setInlineStylesTheme(resourceObjectInstance);
        gui_Label_3.setName("Label_3");
        gui_Label_4.setText("Label");
                gui_Label_4.setInlineStylesTheme(resourceObjectInstance);
        gui_Label_4.setName("Label_4");
        gui_Label_5.setText("Label");
                gui_Label_5.setInlineStylesTheme(resourceObjectInstance);
        gui_Label_5.setName("Label_5");
        gui_Label_6.setText("Label");
                gui_Label_6.setInlineStylesTheme(resourceObjectInstance);
        gui_Label_6.setName("Label_6");
        gui_Label_7.setText("Label");
                gui_Label_7.setInlineStylesTheme(resourceObjectInstance);
        gui_Label_7.setName("Label_7");
        gui_Label_8.setText("Label");
                gui_Label_8.setInlineStylesTheme(resourceObjectInstance);
        gui_Label_8.setName("Label_8");
        gui_Label_9.setText("Label");
                gui_Label_9.setInlineStylesTheme(resourceObjectInstance);
        gui_Label_9.setName("Label_9");
        gui_Box_Layout_Y.addComponent(gui_Label);
        gui_Label_1.setText("Label");
                gui_Label_1.setInlineStylesTheme(resourceObjectInstance);
        gui_Label_1.setName("Label_1");
        gui_Box_Layout_X.setPreferredSizeStr("inherit 111.111115mm");
        gui_Box_Layout_X.setScrollableX(false);
        gui_Box_Layout_X.setScrollableY(false);
                gui_Box_Layout_X.setInlineStylesTheme(resourceObjectInstance);
        gui_Box_Layout_X.setName("Box_Layout_X");
                gui_Box_Layout_X_1.setInlineStylesTheme(resourceObjectInstance);
        gui_Box_Layout_X_1.setName("Box_Layout_X_1");
        gui_Label.setText("Search");
                gui_Label.setInlineStylesTheme(resourceObjectInstance);
        gui_Label.setName("Label");
        addComponent(gui_Label_16);
        addComponent(gui_Label_17);
        gui_Box_Layout_Y.setPreferredSizeStr("inherit 147.61905mm");
                gui_Box_Layout_Y.setInlineStylesTheme(resourceObjectInstance);
        gui_Box_Layout_Y.setName("Box_Layout_Y");
        ((com.codename1.ui.layouts.LayeredLayout)gui_Box_Layout_Y.getParent().getLayout()).setInsets(gui_Box_Layout_Y, "5.291005mm auto 10.526316% auto").setReferenceComponents(gui_Box_Layout_Y, "1 1 -1 1 ").setReferencePositions(gui_Box_Layout_Y, "1.0 0.0 0.0 0.0");
        gui_Label_16.setText("Label");
                gui_Label_16.setInlineStylesTheme(resourceObjectInstance);
        gui_Label_16.setName("Label_16");
        ((com.codename1.ui.layouts.LayeredLayout)gui_Label_16.getParent().getLayout()).setInsets(gui_Label_16, "1.0mm 5.5555573mm 172.48677mm 5.291005mm").setReferenceComponents(gui_Label_16, "-1 -1 -1 -1").setReferencePositions(gui_Label_16, "0.0 0.0 0.0 0.0");
        gui_Label_17.setPreferredSizeStr("161.37566mm inherit");
        gui_Label_17.setText("Label");
                gui_Label_17.setInlineStylesTheme(resourceObjectInstance);
        gui_Label_17.setName("Label_17");
        ((com.codename1.ui.layouts.LayeredLayout)gui_Label_17.getParent().getLayout()).setInsets(gui_Label_17, "3.1746032mm 1.0582061mm auto 0.0mm").setReferenceComponents(gui_Label_17, "0 1 -1 1 ").setReferencePositions(gui_Label_17, "1.0 0.0 0.0 0.0");
    }// </editor-fold>

//-- DON'T EDIT ABOVE THIS LINE!!!
}
